config/routes.rb
Rails.application.routes.draw do
  resources :news, only: [:index, :show]

  get 'about_us', to: 'pages#about_us'
  get 'explore_data', to: 'pages#explore_data'
  get 'explore_stories', to: 'pages#explore_stories'

  root 'pages#home'
end

app/models/administrator.rb
# frozen_string_literal: true

class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
# frozen_string_literal: true

class News < ApplicationRecord
  include ActionView::Helpers::SanitizeHelper

  EXCERPT_LENGTH = 150

  def excerpt
    content = sanitize(body, tags: [])
    if content.length > EXCERPT_LENGTH
      content = "#{content[0...EXCERPT_LENGTH]}..."
    end
    content
  end
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
# frozen_string_literal: true

class NewsController < ApplicationController
  def index
    @news = News.all
  end

  def show
    @news = News.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end

  def explore_data; end

  def explore_story; end

  def about_us; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/flashes_helper.rb
# frozen_string_literal: true

module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice('alert', 'error', 'notice', 'success')
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>
<%= javascript_pack_tag 'application' %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div>
        Protecting Our River
        </div>
      </div>

      <div class="col-sm-8">
        <ul class="social-media">
          <li>
            <a href="https://twitter.com/protectourriver/">
              Twitter
            </a>
          </li>
          <li>
            <a href="https://instagram.com/ProtectingOurRiver/">
              Instagram
            </a>
          </li>
          <li>
            <a href="https://www.facebook.com/ProtectingOurRiver/">
              Facebook
            </a>
          </li>
        <ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand sm-12">
      </div>
    </div>

    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>


        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Explore
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Data', explore_data_path %></a></li>
            <li><%#= link_to 'Stories', explore_stories_path %></a></li>
          </ul>
        </li>

        <li><%= link_to 'About Us', about_us_path %></a></li>
        <li><%= link_to 'News', news_index_path %></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= body_class %>">
  <div id="main-wrapper">
    <%= render partial: "layouts/nav" %>

    <div class="container main-container">
      <% flash.each do |name, msg| -%>
        <%= content_tag :div, sanitize(msg), class: flash_class(name) %>
      <% end -%>
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>

    <%= render partial: "layouts/footer" %>
  <div>

  <%= render "javascript" %>
</body>
</html>

app/views/news/index.html.erb
<h1>News</h1>
<% @news.each do |new| %>
  <div class="news-article">
    <h2><%= link_to new.title, news_path(new) %></h2>
    <div class="meta"><%= new.publish_date %></div>

    <%= new.excerpt %>
    <hr>
  </div>
<% end %>

app/views/news/show.html.erb
<h1><%= @news.title %></h1>
<div class="meta"><%= @news.publish_date %></div>

<%= raw(@news.body) %>

app/views/pages/about_us.html.erb
<h1>Our Mission</h1>

<p>Creating a community to monitor and protect the biodiversity of the L.A.
River System.</p>

<h1>About Us</h1>

<p>Protecting Our River is a community engagement project that mobilizes L.A.
residents from a variety of backgrounds  to help monitor the biodiversity of
the L.A. River and its tributaries. We hope to serve as an example how
scientists, neighborhood leaders, conservationists, writers, community
scientists, educators, students, and artists can work together to deal with
environmental challenges.</p>

<p>Protecting Our River is a project by <a href="https://ucedna.com">CALeDNA</a>,
a University of California community science initiative that  aims to monitor
California’s biodiversity through environmental DNA (eDNA) – the DNA organisms
shed into the environment. Community scientists collect soil samples throughout
California; UC researchers analyze the eDNA in the soil and identify the
microbes, fungi, plants, and animals in the area.</p>

app/views/pages/explore_data.html.erb
<h1>Explore Data</h1>
<p>Data about LA River System will go here.</p>

app/views/pages/explore_stories.html.erb
<h1>Explore Stories</h1>
<p></p>

app/views/pages/home.html.erb
<div class="hero">
  <%= image_tag "Los_Angeles_River.jpg", class: 'hero' %>

  <div class='overlay'>
    <h1>Protecting Our River</h1>
    <p>Together, we can help protect the LA River System's biodiversity.</p>
  </div>
</div>

<br><br>
<h2 style="text-align:center">More info to come...</h2>